version: 0.2

phases:
  install: 
    runtime-versions:
      php: 7.4
  pre_build: # commands to be run before build
    commands:
    - echo Logging in to Amazon ECR 🛎️
    - aws --version
    # login to Elastic container registry
    - eval $(aws ecr get-login --region us-east-1 --no-include-email | sed 's|https://||')
    - REPOSITORY_URI=093838265366.dkr.ecr.us-east-1.amazonaws.com/supermavster/source
    - IMAGE_TAG=1.0
  build:
    commands:
    - echo Build started on `date` 🔧
    
    - echo Creating .env files
    - cp .env.example .env
    - cp source/.env.example source/.env
    
    - echo Update Config
    - apt update -y && apt upgrade -y

    - echo ADD Config
    - apt-get install sudo -y
    - sudo adduser $(whoami) sudo
    - sudo groupadd docker
    - sudo usermod -aG docker $(whoami)

    - echo Update Config
    - sudo apt update -y && sudo apt upgrade -y

    - echo Building the Docker image
    - docker-compose build
    
    - echo Install Components
    - docker-compose run --rm composer install
    - docker-compose run --rm npm install

    - echo Generating app key
    - docker-compose run --rm artisan key:generate
  post_build:
    commands:
      - echo Build completed on `date`  🚀
      - echo Pushing the Docker image
      - docker image ls -a
      - docker push $REPOSITORY_URI:$IMAGE_TAG