version: 0.2

phases:
  install: 
    runtime-versions:
      php: 7.4
  pre_build: # commands to be run before build
    commands:
    - echo Logging in to Amazon ECR 🛎️
    - aws --version
    # login to Elastic container registry
    - eval $(aws ecr get-login --region us-east-1 --no-include-email | sed 's|https://||')
    - REPOSITORY_URI=093838265366.dkr.ecr.us-east-1.amazonaws.com/supermavster/source
    - IMAGE_TAG=1.0
  build:
    commands:
    - echo Build started on `date` 🔧
    
    - echo Creating .env files
    - cp .env.example .env
    - cp source/.env.example source/.env
    
    - echo Update Config
    - apt update -y && apt upgrade -y

    - echo ADD Config
    - apt-get install sudo -y
    - sudo adduser $(whoami) sudo
    - sudo groupadd docker
    - sudo usermod -aG docker $(whoami)


    - echo Upgrade Info
    - sudo apt update -y && sudo apt upgrade -y
    - sudo apt-get install linux-image-$(uname -r)


    - echo Update Config
    - sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo apt-key fingerprint 0EBFCD88
    - sudo add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo apt-key fingerprint 0EBFCD88
    - sudo add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - echo composer
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    - docker-compose --version
    
    - echo Docker
    - docker -v

    - echo Building the Docker image
    - sudo dockerd
    - sudo docker-compose build
    
    - echo Install Components
    - sudo docker-compose run --rm composer install
    - sudo docker-compose run --rm npm install

    - echo Generating app key
    - sudo docker-compose run --rm artisan key:generate
  post_build:
    commands:
      - echo Build completed on `date`  🚀
      - echo Pushing the Docker image
      - sudo docker image ls -a
      - sudo docker push $REPOSITORY_URI:$IMAGE_TAG